// Sets up the parser generated by canopy to use the
// [Node](../node.html) subclasses in the generated tree. This is all
// a bit of a hack that is dependent on how canopy creates nodes in its parse
// tree.
import grammar from './grammar.peg';
import parser from '../parser.js';

export default parser(grammar);
